### PR TITLE
tctl: Add spinner to long running commands [p2]

### PR DESCRIPTION
**Pull request by feedmeapples**
- Origin issue: 

# Summary

Adds spinner and progress bar for potentially long running commands. Makes tctl feel more responsive

# Basic example

# Motivation

Some commands may take long time until they will show output or an error (typically context timeout). This makes tctl feel unresponsive and slow. Proposal addresses these issues adding responsiveness  

# Detailed design

in doc

# Drawbacks

-

# Alternatives

-

# Adoption strategy

not a breaking change

# How we teach this

-

### CODE REVIEW

**Review by robholland — COMMENTED** [review]
Could do with some examples of long running commands here.

**Comment by bergundy** [comment]
We should make sure that indicators are only shown when output is a TTY because it will conflict with piping.

**Comment by robzienert** [comment]
It'd be nice to have a flag to dictate this as well.

**Comment by feedmeapples** [comment]
> We should make sure that indicators are only shown when output is a TTY because it will conflict with piping.

yup, this is covered

**Comment by feedmeapples** [comment]
> It'd be nice to have a flag to dictate this as well.

Updated the terminology to "spinner" and "progress bar",  specified `--no-progress` in the doc (similar to [npm --no-progress](https://github.com/npm/npm/issues/8704#issuecomment-158222250))

**Comment by feedmeapples** [comment]
this proposal is on hold rn, focused on implementing higher priority proposals and releasing tctl. Afterwards planning to finish and implement this proposal

**Comment by bergundy** [comment]
This is outdated. Closing due to lack of motivation.

**Pull request closed without merging**
